CREATE OR REPLACE TRIGGER STUD_TRIG AFTER INSERT ON STUD_FILE
FOR EACH ROW
DECLARE
TOT NUMBER:=0;
BEGIN
TOT:=:NEW.M1+:NEW.M2;
INSERT INTO STUD_MARK VALUES(:NEW.SID,TOT);
DBMS_OUTPUT.PUT_LINE('AFTER INSERT trigger activated:');
END;
/
